### ISSUE TITLE
Explain how to upgrade existing installation

### ISSUE THREAD

**Issue by schlomo** [BlissRoms-x86/website#1]
Great work, using it as digital signage solution for our kitchen.

I can't find any infos on updating or upgrading an existing installation to the next version and would be happy to contribute an update/upgrade guide if you can point me to some infos.

**Comment by electrikjesus** [comment]
Two ways, depending on install method. 
If installed using bootable USB, follow the Auto Update instructions from https://www.android-x86.org/installhowto.html
If installed using the Windows Installer, open the .iso with 7zip, double click on the system.sfs, and drag the system.img inside to replace the system.img in the install folder. Then follow up with the kernel, initrd (and ramdisk if on pie)
